### PR TITLE
Update to the most recent code

### PR DESCRIPTION
**Pull request by shinyichen**

### CODE REVIEW

**Comment by GreatYYX** [comment]
can you transfer related repos' ownership to our org and update configs?

**Comment by shinyichen** [comment]
@GreatYYX 
The submodule `AIDA-Interchange-Format` belongs to Next Century: `https://github.com/NextCenturyCorporation/AIDA-Interchange-Format`.
The submodule `gaia-clustering` is already on `https://github.com/usc-isi-i2/gaia-clustering`.

The config in the pull request should reflect that already.

**Comment by shinyichen** [comment]
I see `AIDA-Interchange-Format` is pointing to my forked version. I will update that.

**Comment by GreatYYX** [comment]
@shinyichen by saying "related repos", I meant all gaia repos under your name. Looks like those repos are all forked from usc-isi-i2, so no need to change. Thanks.

**Pull request merged**
